trigger:
- main
strategy:
 matrix:
  linux:
   operatingSystem: 'ubutu-latest'
  mac:
   operatingSystem: 'macos-latest'


pool:
  vmImage: $(operatingSystem)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


