trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publicKey
  inputs:
      secureFile: 'azure_certs.pub'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'Free Trial(3fb9374b-9b78-41d2-b07c-3dde2f038555)'
    backendAzureRmSubscriptionId: '3fb9374b-9b78-41d2-b07c-3dde2f038555'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'cloud-shell-storage-southcentralus'
    backendAzureRmResourceGroupLocation: 'South Central US'
    backendAzureRmStorageAccountName: 'cs710032001ee38abcb'
    backendAzureRmContainerName: 'storageaccountcontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
    allowTelemetryCollection: true
